[virtualenvs]
in-project = true

[repositories]
[repositories.ldev]
url = "http://pypi.ldev.eu.langlauf.tech/simple/"

[repositories.llstage]
url = "https://pypisrv.stage.eu.langlauf.tech/simple/"

[repositories.llprod]
url = "https://pypi.eu.langlauf.tech/simple/"
